name: "Sync GitHub Labels"

permissions:
  contents: read
  issues: write

on:
  push:
    paths:
      - .github/labels/issue-label.yml
      - .github/workflows/sync-issue-labels.yaml

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync labels from config
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels/issue-label.yml
